export const issues = [ {
        image: '/images/AuthoritarianCruelty.jpg',
        topic: 'Authoritarian Cruelty',
        blurb: 'Jack Ciattarelli has embraced tactics that echo authoritarian playbooks. He backed Trump\'s deployment of the National Guard in cities like Portland and Chicago, despite <a href="https://factcheck.org/2020/06/trumps-false-claim-about-crime-in-democratic-run-cities" target="_blank">crime rates already trending downward</a>. He campaigned with election deniers and conspiracy theorists like <a href="https://democraticgovernors.org/updates/100-maga-jack-ciattarelli-shows-his-true-colors-by-rallying-with-extremist-maga-stars" target="_blank">Scott Presler</a> and <a href="https://www.adl.org/resources/backgrounder/jack-posobiec" target="_blank">Jack Posobiec</a>, and downplayed Trump\'s threat to <a href="https://www.msn.com/en-us/news/politics/flip-flop-jack-ciattarelli-pushed-for-gateway-tunnel-project-in-2017/ar-AA1OoOL9" target="_blank">block Gateway Tunnel funding</a> as a \'negotiating tactic\' before finally breaking with him under pressure.\n\nWhen Mikie Sherrill questioned Ciattarelli\'s past role in publishing opioid marketing materials, part of a broader pattern of <a href="https://www.nytimes.com/2022/07/08/health/opioid-settlement-purdue.html" target="_blank">industry-funded misinformation</a>, Jack responded by <a href="https://www.nj.com/politics/2025/10/ciattarelli-sues-sherrill-over-opioid-attack-ad.html" target="_blank">suing her for defamation</a>, rather than addressing the substance. Sherrill also called for a <a href="https://www.politico.com/news/2025/09/25/house-investigation-mikie-sherrill-military-records-00581091" target="_blank">House investigation into the illegal release of her military records</a>, which included her Social Security number and personal information about her family. Her campaign accused Trump allies of coordinating the breach. Ciattarelli\'s instinct is to punish critics and weaponize institutions. That\'s not leadership, it\'s retaliation.'
    },
    {
        image: '/images/GovernmentOverreach.jpg',
        topic: 'Federal Government Overreach',
        blurb: 'Jack Ciattarelli says he\'ll “get big government out of the way,” but he\'s stayed quiet while Trump expands federal power to punish political enemies. Trump recently directed the DOJ to indict former FBI Director James Comey and New York Attorney General Letitia James, both of whom investigated him, triggering widespread concern over the <a href="https://time.com/7321683/trump-political-opponents-doj-prosecution" target="_blank">politicization of federal law enforcement</a>. Legal experts have called the charges \'vindictive\' and \'selective,\' noting that <a href="https://san.com/cc/trump-names-new-prosecution-targets-as-experts-criticize-doj-politicization" target="_blank">Trump publicly demanded their prosecution just days before indictments were filed</a>.\n\nCiattarelli has not condemned these actions. He also remained silent when Trump stood beside the Attorney General and FBI Director to announce \'Operation Summer Heat,\' a vague initiative that included <a href="https://www.msn.com/en-us/news/politics/maddow-blog-trump-pitches-justice-dept-and-fbi-leaders-on-a-newly-expanded-enemies-list/ar-AA1OAIb4" target="_blank">calls to prosecute additional political foes</a>. Jack has echoed Trump\'s rhetoric about \'weaponized government,\' but only when it suits his narrative. When federal power is used to settle scores, Ciattarelli doesn\'t push back, he looks the other way.'
    },
    {
        image: '/images/EnergyEnvironment.jpg',
        topic: 'Energy & Environment',
        blurb: 'Jack Ciattarelli used to say climate change is real and caused by humans. In 2017, he called for reducing carbon emissions and transitioning to cleaner energy. But since aligning with Trump, he\'s reversed course, praising Trump\'s EPA while staying silent as it rolled back <a href="https://www.politico.com/news/2025/06/11/trumps-epa-to-revoke-bidens-climate-rule-on-power-plants-00394336" target="_blank">power plant rules</a>, <a href="https://gmauthority.com/blog/2025/03/trump-administration-begins-rolling-back-epa-vehicle-emissions-rules" target="_blank">vehicle emissions standards</a>, and <a href="https://earthjustice.org/press/2025/clean-water-in-the-crosshairs-as-trumps-epa-signals-new-deregulatory-efforts" target="_blank">clean water protections</a>. He opposed offshore wind development and criticized solar incentives, even as Trump expanded <a href="https://www.fastcompany.com/91422529/sable-california-oil-spill-trump-administration" target="_blank">oil drilling in protected areas</a> and opened <a href="https://www.pbs.org/newshour/nation/trump-to-open-more-federal-land-for-coal-mining-provide-industry-625m-to-boost-coal-plants" target="_blank">13 million acres of federal land for coal mining</a>.\n\nMikie Sherrill has proposed <a href="https://www.mikiesherrill.com/affordability-agenda" target="_blank">freezing energy rates</a> to protect families from price spikes, while accelerating grid upgrades and clean energy investments and incentives. Jack\'s policies favor fossil fuel expansion and deregulation. Mikie\'s approach balances affordability with long-term resilience.'
    },
    {
        image: '/images/Immigration.jpg',
        topic: 'Immigration',
        blurb: 'Jack Ciattarelli pledged to <a href="https://www.foxnews.com/politics/gop-candidate-rips-blue-state-directive-meddling-police-forces-cooperation-with-ice-handcuffed" target="_blank">end all sanctuary policies on \'Day One\'</a>, backing Trump\'s crackdown even as ICE raids in 2025 draw national outrage and straining our local police departments. In Chicago, masked and unidentified agents held a <a href="https://www.reuters.com/world/us/us-border-patrol-raid-sweeps-citizens-families-chicago-crackdown-intensifies-2025-10-04/" target="_blank">military-style raid a residential complex</a>, detaining some U.S. citizens for hours and even <a href="https://www.politico.com/news/magazine/2025/10/14/former-ice-director-q-a-00603916" target="_blank">shot a pastor with a pepper ball while he prayed</a>. ICE agents are not required to Mirandize detainees unless conducting custodial interrogation, and they can detain citizens if they claim \'reasonable suspicion.\' Trump\'s <a href="https://factually.co/fact-checks/politics/trump-ice-funding-a8fc9f" target="_blank">budgets and executive orders</a> granted ICE unlimited funding and removed oversight. Mikie Sherrill <a href="https://sherrill.house.gov/media/press-releases/sherrill-pushes-for-improved-border-security-and-comprehensive-immigration-reform-urges-house-speaker-to-take-action" target="_blank">called for reform</a>. Jack stayed silent.'
    },
    {
        image: '/images/PublicEducation.jpg',
        topic: 'Education',
        blurb: 'New Jersey\'s public schools are <a href="https://worldpopulationreview.com/state-rankings/public-school-rankings-by-state" target="_blank">ranked #3 in the nation</a>, thanks to insanely talented teachers, strong teacher pay, real history education, and inclusive classrooms. Jack Ciattarelli wants to take us backward. He\'s stayed quiet while Trump pushes <a href="https://newjerseyglobe.com/education/ciattarelli-ad-hits-sherrill-on-lgbtq-education-in-schools/" target="_blank">book bans targeting LGBTQ+ families</a> and <a href="https://www.americanprogress.org/article/public-education-under-threat-4-trump-administration-actions-to-watch-in-the-2025-26-school-year/" target="_blank">defunds diversity programs</a>. Trump\'s 2025 budget proposes a <a href="https://www.kpbs.org/news/education/2025/06/02/trumps-budget-calls-for-a-15-funding-cut-to-the-education-department" target="_blank">15% cut to the Department of Education</a>, slashing $4.5 billion from K–12 programs and <a href="https://www.msn.com/en-us/news/politics/exclusive-trump-administration-targets-college-prep-program-republicans-defended-sources-say/ar-AA1OsXrp" target="_blank">gutting college prep support</a>. Mikie Sherrill wants to invest in struggling districts, not turn New Jersey into Kentucky or Louisiana.'
    },
    {
        image: '/images/PublicFunding.jpg',
        topic: 'Public Funding',
        blurb: 'Trump <a href="https://nj1015.com/trump-axes-18b-gateway-tunnel/" target="_blank">froze $18 billion in Gateway Tunnel funding</a> — a project vital to 200,000 daily commuters and thousands of union jobs. Jack Ciattarelli initially downplayed the threat as \'negotiation,\' only <a href="https://www.yahoo.com/news/articles/future-hudson-rail-tunnels-again-180122418.html" target="_blank">breaking ranks</a> after Trump officially terminated the project. Mikie Sherrill has fought for Gateway since day one.\n\nTrump also cut <a href="https://federalnewsnetwork.com/budget/2025/08/trump-blocks-4-9b-in-foreign-aid-congress-okd-using-maneuver-last-seen-nearly-50-years-ago/" target="_blank">$4.9 billion in foreign aid</a>, shuttering HIV clinics in Lesotho and pushing <a href="https://www.msn.com/en-us/news/world/un-agency-says-137-million-people-face-severe-hunger-due-to-global-aid-cuts/ar-AA1OB6qN" target="_blank">13.7 million people toward famine</a>. Meanwhile, he\'s defunding FEMA by 32% and NOAA by 27%, <a href="https://thehill.com/policy/energy-environment/5329529-epa-park-service-noaa-trump-budget-cuts/" target="_blank">crippling disaster response</a> while prioritizing cruel immigration policies.\n\nIn New Jersey, Trump\'s budget eliminates $1.1 billion for public broadcasting, forcing <a href="https://www.msn.com/en-us/news/politics/pbs-shutting-down-in-an-entire-state-thanks-to-trump-s-cuts/ar-AA1NiAcQ" target="_blank">NJ PBS to prepare for closure</a> and <a href="https://nj1015.com/new-jersey-public-broadcasting-cuts/" target="_blank">gutting $23 million from local stations</a>. Trump and Jack prefer media owned by billionaires, especially ones Trump handpicks. Mikie Sherrill stands up for public infrastructure, public media, and public safety. Jack stands aside.\n\n<a href="https://www.youtube.com/shorts/RKGoyTOe5zI" target="_blank">Jack also explicity AVOIDED a vote to fund pensions for NJ police officers, firefighters, and teachers</a>. He doesn\'t understand our priorities.'
    },
    {
        image: '/images/Healthcare.jpg',
        topic: 'Healthcare',
        blurb: 'Jack Ciattarelli says he\'ll never support cuts to Medicare, but Trump\'s 2025 budget tells a different story. It triggers up to <a href="https://www.medicalnewstoday.com/articles/how-will-older-adults-affected-trump-one-big-beautiful-bill-medicare-medicaid" target="_blank">$500 billion in Medicare reductions</a> through automatic PAYGO rules, slashing payments to doctors, hospitals, and nursing homes. That means fewer providers will accept Medicare, and seniors could lose access to specialists, rehab, and even primary care.\n\nThe budget also launches a <a href="https://www.forbes.com/sites/howardgleckman/2025/07/30/what-older-adults-need-to-know-about-trumps-changes-to-medicare/" target="_blank">six-state pilot program including New Jersey, requiring <b>prior authorization</b></a> for 17 procedures under traditional Medicare, including back surgeries, steroid injections, and knee arthroscopies. New Jersey is one of the test states. Seniors will need government approval before receiving care, and AI will screen requests before any human review.\n\nTrump\'s plan also <a href="https://www.afscme.org/about/downloadable-asset/Impact-of-the-so-called-Big-Beautiful-Bill-on-Retirees.pdf" target="_blank">exempts more drugs from price negotiation</a>, raising out-of-pocket costs for prescriptions like cancer and arthritis treatments. Mikie Sherrill has fought to protect Medicare access and lower drug prices. Jack stays silent while Trump rewrites the rules.'
    },
    {
        image: '/images/RightsFreedoms.jpg',
        topic: 'Rights & Freedoms',
        blurb: 'Trump and his allies are attacking core freedoms - speech, protest, marriage, and the right to vote. After the killing of Charlie Kirk, Trump falsely claimed that \'most of the violence is on the left,\' while data shows <a href="https://time.com/7317383/political-violence-america-trump-crackdown-right/" target="_blank">right-wing extremists are responsible for 63% of political violence deaths since 1975</a>.\n\nJack Ciattarelli <a href="https://glaad.org/election-2025-nj-gov-candidates-record-lgbtq/" target="_blank">voted against codifying marriage equality</a> and pledged to <a href="https://newjerseystatecannabis.org/news-20aug2025" target="_blank">roll back recreational cannabis legalization</a>, opposing personal freedom and defying libertarian principles.\n\nTrump <a href="https://mississippitoday.org/2025/01/05/trump-free-speech-press-lawsuits/" target="_blank">has sued TV networks and newspapers over unfavorable coverage</a>, including ABC News and the Des Moines Register while claiming to defend free speech. He\'s pushed a <a href="https://www.nilc.org/articles/trump-registry-plans-what-we-know-so-far/" target="_blank">national protest registry</a> and backed efforts to <a href="https://www.msn.com/en-us/news/politics/the-supreme-court-is-going-to-gut-the-voting-rights-act-to-the-bone/ar-AA1OxB7G" target="_blank">gut the Voting Rights Act</a> and <a href="https://www.motherjones.com/politics/2025/08/republican-racial-gerrymandering/" target="_blank">legalize extreme gerrymandering</a>.\n\nMikie Sherrill defends free speech, equal rights, and due process. Jack defends Trump, even when it undermines the Constitution.'
    },
    {
        image: '/images/TaxationSpending.jpg',
        topic: 'Taxation & Spending',
        blurb: 'Jack Ciattarelli says he\'ll make NJ affordable, but he\'s <a href="https://jerseyindependent.com/Elections/ciattarelli-has-supported-tax-increases-and-opposed-tax-relief" target="_blank">raised taxes his entire career</a>, from payroll to sales to gas, while Mikie Sherrill has never voted to raise taxes on working families. Jack\'s tax policy puts everything on the table <i>except</i> taxing millionaires—his running mate even said \'<a href="https://www.msn.com/en-us/news/politics/gop-lt-gov-candidate-says-taxes-are-on-the-table-but-we-can-t-just-beat-up-on-the-millionaires/ar-AA1NGTIp" target="_blank">we can\'t just beat up on the millionaires</a>.\' Jack wants a Trump-style <a href="https://democraticgovernors.org/updates/new-jersey-gop-gov-candidates-want-to-bring-doges-disasters-to-the-garden-state/" target="_blank">NJDOGE agency to slash services and implement mass layoffs</a>. <a href="https://www.mikiesherrill.com/transparency.pdf" target="_blank">Mikie offers a New Jersey Report Card to track spending</a> and improve outcomes. <a href="https://www.msn.com/en-us/politics/government/grocery-prices-are-rising-trump-s-focused-on-everything-else/ar-AA1OBzZO" target="_blank">Jack backs Trump\'s tariffs, which fuel inflation</a>. Mikie stands for smart, stable policy—not chaos.'
    }
]