export const formatUrl = (url) => {
    return url
        .replace(/^https?:\/\//, '')
        .replace(/^www\./, '')
}

export const truncateText = (text, maxLength) => {
    if (text.length <= maxLength) {
        return text
    }
    return text.slice(0, maxLength) + '...'
}

export const sampleResponse = {
    "question1": "no",
    "question2": "no",
    "question3": "no",
    "question4": "no",
    "question5": "no",
    "question6": "no",
    "question7": "no",
    "question8": "yes",
    "question9": "yes",
    "question10": "yes",
    "question11": "no-2",
    "question12": "yes",
    "question13": "yes",
    "question14": "no-2",
    "question15": "no",
    "question16": "no",
    "question17": "yes-2",
    "question18": "yes",
    "question19": "no-2",
    "question20": "yes",
    "question21": "yes",
    "question22": "yes",
    "question23": "yes",
    "question24": "no",
    "question25": "yes",
    "question26": "no",
    "question27": "no",
    "question28": "yes",
    "question29": "no",
    "question30": "no",
    "question31": "yes",
    "question32": "no",
    "question32-Comment": "If the non-violent crimes hurt people but not physically and are likely to be repeated, then Yes.",
    "question33": "no",
    "question34": "yes",
    "question35": "no",
    "question36": "no",
    "question37": "no",
    "question38": "yes",
    "question39": "no",
    "question40": "yes",
    "question41": "yes",
    "question42": "yes",
    "question43": "yes",
    "question44": "yes",
    "question45": "yes",
    "question46": "no",
    "question47": "no",
    "question48": "no",
    "question49": "no",
    "question50": "yes",
    "question51": "yes",
    "question52": "no",
    "question53": "yes",
    "question54": "yes",
    "question55": "yes",
    "question56": "yes",
    "question57": "yes",
    "question58": "yes",
    "question59": "yes",
    "question60": "yes",
    "question61": "yes",
    "question62": "yes",
    "question63": "yes",
    "question64": "yes",
    "question65": "no",
    "question66": "no",
    "question67": "no",
    "question68": "yes",
    "question69": "no",
    "question69-Comment": "If a policy like Universal Healthcare was paid for by taxes from the middle class, these would have to be more than offset, for all middle class tax brackets, by healthcare savings.",
    "question70": "no",
    "question71": "no",
    "question72": "no",
    "question73": "yes-2",
    "question73-Comment": "Conditions on the humane treatment of Palestinians and removing illegal settlements.",
    "question74": "yes",
    "question75": "no",
    "question76": "yes-2",
    "question76-Comment": "Mutual recognition and no military role for Hamas",
    "question77": "no",
    "question78": "yes-2",
    "question79": "yes",
    "question80": "yes",
    "question80-Comment": "Specifically in the strikes on Iran",
    "question81": "yes",
    "question82": "yes",
    "question83": "yes",
    "question84": "yes",
    "question85": "no",
    "question85-Comment": "Blind trust",
    "question86": "no",
    "question86-Comment": "This was a ridiculous grift",
    "question87": "no",
    "question88": "no",
    "question89": "no",
    "question90": "no",
    "question91": "no",
    "question92": "yes",
    "question93": "no",
    "question94": "yes",
    "question95": "yes-2",
    "question96": "yes",
    "question97": "yes",
    "question98": "taylor-ham",
    "question98-Comment": "Taylor Ham is a brand of Pork Roll from Taylor Provisions. Whatever you call it, it\u0027s welcome on my Egg \u0026amp; Cheese sandwich.",
    "question99": "I want candidates in every Primary and Competitive Midterm Election to be informed about their candidates and positions so they can easily compare and make informed decisions with their votes. I believe that informed voters will lead to better candidates.",
    "question100": "LS1234",
    "HappendAt": "\/Date(1764714013682)\/",
    "InstanceId": null
}